Attaches Tool 2.0
editor-js/attaches pull request #1
Opened 2019-05-01 12:19 UTC by PolinaShneider

Test it here: https://github.com/codex-team/editor.js/tree/attaches-tool-test

![image](https://user-images.githubusercontent.com/15448200/57016721-69227880-6c24-11e9-8216-76540efd3348.png)

2019-05-01 15:21 UTC, gohabereg requested changes

2019-05-01 15:21 UTC, gohabereg commented on src/index.js
> +export default class Attaches {
Может лучше AttachesTool?

2019-05-01 15:21 UTC, gohabereg commented on src/index.js
> +      Object.assign(this.data, {
Вроде в сеттере и так assign, можно просто написать `this.data = {...}`

2019-05-01 15:21 UTC, gohabereg commented on src/index.js
> +    this.uploader = new Uploader({
Было бы неплохо сразу сделать возможность передавать кастомный аплоадер, так же как сейчас в плагине картинки

2019-05-30 17:42 UTC, neSpecc requested changes

2019-05-30 17:42 UTC, neSpecc commented on src/index.js
> +    this.nodes.wrapper = this.make('div', [this.CSS.baseClass, this.CSS.wrapper]);
у тебя обертка выглядит как кнопка, а сама кнопка имеет невидимые границы

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/3684889/58649323-7bbbca80-8314-11e9-9f3c-99576336ebf6.png">

2019-05-30 17:42 UTC, neSpecc commented on src/index.js
> +    this.nodes.wrapper = this.make('div', [this.CSS.baseClass, this.CSS.wrapper]);
обертка должна остаться оберткой, в которую завернута кнопка. Иначе отступы обертки не будут работать

2019-05-30 17:42 UTC, neSpecc commented on src/index.js
> +      button: 'cdx-attaches__button',
нужно использовать стили из апи: https://editorjs.io/styles#button

2019-05-30 17:42 UTC, neSpecc commented on src/index.css
> +            background: url('data:image/svg+xml,<svg height="48" width="48" xmlns="http://www.w3.org/2000/svg"><path clip-rule="evenodd" d="M37 47H11a4 4 0 0 1-4-4V5a4 4 0 0 1 4-4h19c.32 0 .593.161.7
это не сработает

2019-05-30 17:42 UTC, neSpecc commented on src/index.js
> +        // TODO: add loader
лоадер надо добавить

2019-05-30 17:42 UTC, neSpecc commented on src/index.js
> +      this.showFileData();
после загрузки надо поставить курсор в title

2019-06-04 14:08 UTC, neSpecc requested changes
- Показывать выбор файла сразу после клика на кнопку в тулбоксе
- Надо отделить кнопку аплоада и срендеренный виджет файла (сейчас последний выглядит как кнопка с ховером и тд)
- при ширине в 320 расширение выезжает за блок
- на кнопке загрузки текст и иконка не выровнены по центру по вертикали

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +    this.nodes.holder = this.make('div', [this.CSS.holder, this.CSS.button]);
это не holder, а button

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +    };
в конфиг надо добавить поле `buttonText`

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +   * @param config
ну указаны типы данных

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +    this.nodes.title.setAttribute('contentEditable', true);
это текст на кнопке, а не поле ввода тайтла.

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +      this.uploadingFailed('File upload failed');
`errorText` тоже лучше вынести в конфиг (опциональное поле)

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +      this.uploadingFailed('File upload failed');
как и все тексты

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +      this.nodes.title.innerHTML = this.config.placeholder || `${Icon} Upload`;
дефолтный `buttonText` -> `Select file`

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +    const { body: { success, file } } = response;
будет ошибка, если ответ придет в другом формате. Ошибка нигде не обрабатывается

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +   * @param {UploadResponseFormat} response
где задается этот тип?

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +    setTimeout(() => this.nodes.holder.classList.remove(this.CSS.holderLoading, this.CSS.loader), 500);
откуда цифра 500?

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +    const size = this.make('div', this.CSS.size);
size, extension — опциональные поля, их может не быть.

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> + * @property {string} name
- не помечены опциональные поля (с помощью `[]`). 
- Данные о файле лучше завернуть в `file`. 
- У `file` нет обязательных полей, все опциональные, то есть `name`, `size`, `extension` надо описать в ридми как опциональные для дизайна
- все, что вернул сервер в поле `file` надо сохранить в поле `file`

2019-06-04 14:08 UTC, neSpecc commented on src/index.js
> +      placeholder: config.placeholder
плейсхолдер используется для чего? пусть выводится в пустом инпукте title. Назвать лучше `titlePlaceholder`

2019-06-19 05:55 UTC, wotta commented
Hello everyone, Sorry kinda intruding in this issue but I would like to know what the status is for this issue?

We are getting a ticket in the sprint which requires this functionality so if this will take a bit longer I can dismiss the ticket from our sprint to the next one 🙂

2019-07-15 15:44 UTC, neSpecc requested changes

2019-07-15 15:44 UTC, neSpecc commented on README.md
> +| size           |`number`   | File's size                       |
Надо написать, что в дизайне ожидается размер в байтах

2019-07-15 15:44 UTC, neSpecc commented on src/index.js
> +      const title = toolsContent.querySelector(`.${this.CSS.title}`).textContent;
пользователи могут активировать инлайн-тулбар при желании, так что лучше брать innerHTML

2019-07-15 15:44 UTC, neSpecc commented on src/index.js
> +          size: (size / 1000).toFixed(1) // size in KB
тут ты перезаписываешь значение, пришедшее тебе с сервера. Лучше делать это только на выводе. В идеале еще поддержать MiB

2019-07-15 15:44 UTC, neSpecc commented on src/index.js
> +    switch (extension.toLowerCase()) {
вынеси отдельный словарь этот объект
```
{
   doc: '#3e74da',
   pdf: '#d47373',
   ...
}
```

2019-07-15 15:44 UTC, neSpecc commented on src/index.js
> +      {
лишние скобки

2019-07-15 15:44 UTC, neSpecc commented on src/index.js
> +      fileIcon.querySelector('svg').style.fill = extensionColor;
вместо этого можно в css задать для этого svg `fill: currentColor`

2019-07-15 21:38 UTC, neSpecc approved these changes

2019-07-15 22:08 UTC, dimensi commented
@PolinaShneider, @neSpecc могли бы вы добавить то те же возможности по загрузке, что в image tool?

2019-07-16 04:48 UTC, neSpecc commented
> @PolinaShneider, @neSpecc могли бы вы добавить те же возможности по загрузке, что в image tool?

этот реквест слишком долго висит, так что сначала смерджим его в таком виде. Для кастомного аплоадера надо создать issue и сделать отдельным реквестом.

2019-07-17 13:35 UTC, gohabereg approved these changes

2019-07-17 18:13 UTC, merged